"""add_github_oauth_columns

Revision ID: 0996aff93fe7
Revises: d359a92d0ae1
Create Date: 2026-03-21 20:34:51.407573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0996aff93fe7"
down_revision: Union[str, Sequence[str], None] = "d359a92d0ae1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("creators", schema=None) as batch_op:
        batch_op.add_column(sa.Column("github_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("github_username", sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f("ix_creators_github_id"), ["github_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("creators", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creators_github_id"))
        batch_op.drop_column("github_username")
        batch_op.drop_column("github_id")

    # ### end Alembic commands ###
