"""add_follows_and_signal_comments_tables

Revision ID: 2cfb0e3dd9e3
Revises: 48e054e14852
Create Date: 2026-03-23 10:24:01.153041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfb0e3dd9e3'
down_revision: Union[str, Sequence[str], None] = '48e054e14852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.String(length=64), nullable=False),
    sa.Column('followed_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('follower_id != followed_id', name='ck_no_self_follow'),
    sa.ForeignKeyConstraint(['followed_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follow_pair')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('ix_follows_followed_id', ['followed_id'], unique=False)
        batch_op.create_index('ix_follows_follower_id', ['follower_id'], unique=False)

    op.create_table('signal_comments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.signal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_comments', schema=None) as batch_op:
        batch_op.create_index('ix_signal_comments_creator_id', ['creator_id'], unique=False)
        batch_op.create_index('ix_signal_comments_signal_id', ['signal_id'], unique=False)

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key(None, 'creators', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('signal_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_signal_comments_signal_id')
        batch_op.drop_index('ix_signal_comments_creator_id')

    op.drop_table('signal_comments')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('ix_follows_follower_id')
        batch_op.drop_index('ix_follows_followed_id')

    op.drop_table('follows')
    # ### end Alembic commands ###
