"""add_tos_consent_columns

Revision ID: 31ef208347da
Revises: dbdb51ff0a27
Create Date: 2026-04-18 01:26:33.759761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ef208347da'
down_revision: Union[str, Sequence[str], None] = 'dbdb51ff0a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tos_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('tos_accepted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('tos_accepted_at')
        batch_op.drop_column('tos_hash')

    # ### end Alembic commands ###
