"""add_api_key_hash_v2_bcrypt

Revision ID: 55de4aad29f5
Revises: a9c1e2f3b4d5
Create Date: 2026-04-18 00:58:24.437976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55de4aad29f5'
down_revision: Union[str, Sequence[str], None] = 'a9c1e2f3b4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key_hash_v2', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('api_key_hash_v2')

    # ### end Alembic commands ###
