"""add bot_templates table

Revision ID: a71d4350bc0d
Revises: 064a5d651473
Create Date: 2026-03-23 09:59:20.235021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71d4350bc0d'
down_revision: Union[str, Sequence[str], None] = '064a5d651473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_templates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strategy_type', sa.String(length=32), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('fork_count', sa.Integer(), nullable=False),
    sa.Column('forked_from_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("strategy_type IN ('momentum','mean_reversion','sentiment','volatility','custom')", name='ck_strategy_type'),
    sa.CheckConstraint('version >= 1', name='ck_template_version'),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['forked_from_id'], ['bot_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_templates', schema=None) as batch_op:
        batch_op.create_index('ix_bot_templates_creator_id', ['creator_id'], unique=False)
        batch_op.create_index('ix_bot_templates_is_public', ['is_public'], unique=False)
        batch_op.create_index('ix_bot_templates_strategy_type', ['strategy_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_bot_templates_strategy_type')
        batch_op.drop_index('ix_bot_templates_is_public')
        batch_op.drop_index('ix_bot_templates_creator_id')

    op.drop_table('bot_templates')
    # ### end Alembic commands ###
