"""add elo rating matchmaking tables

Revision ID: b80988abf0e5
Revises: a3c7e1f4b829
Create Date: 2026-03-22 21:03:05.326813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80988abf0e5'
down_revision: Union[str, Sequence[str], None] = 'a3c7e1f4b829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_ratings',
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('elo', sa.Float(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('bot_id')
    )
    op.create_table('matchmaking_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id')
    )
    with op.batch_alter_table('matchmaking_queue', schema=None) as batch_op:
        batch_op.create_index('ix_matchmaking_queue_bot_id', ['bot_id'], unique=True)

    op.create_table('rating_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('elo', sa.Float(), nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['battles.battle_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.create_index('ix_rating_history_bot_id', ['bot_id'], unique=False)
        batch_op.create_index('ix_rating_history_timestamp', ['timestamp'], unique=False)

    op.create_table('tournament_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament_id', sa.String(length=64), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('match_order', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.String(length=64), nullable=True),
    sa.Column('winner_bot_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.battle_id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['winner_bot_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_matches', schema=None) as batch_op:
        batch_op.create_index('ix_tournament_matches_battle_id', ['battle_id'], unique=False)
        batch_op.create_index('ix_tournament_matches_tournament_id', ['tournament_id'], unique=False)

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key('fk_tournaments_created_by', 'creators', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournaments_created_by', type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('tournament_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_tournament_matches_tournament_id')
        batch_op.drop_index('ix_tournament_matches_battle_id')

    op.drop_table('tournament_matches')
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.drop_index('ix_rating_history_timestamp')
        batch_op.drop_index('ix_rating_history_bot_id')

    op.drop_table('rating_history')
    with op.batch_alter_table('matchmaking_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_matchmaking_queue_bot_id')

    op.drop_table('matchmaking_queue')
    op.drop_table('bot_ratings')
    # ### end Alembic commands ###
