"""initial schema

Revision ID: d359a92d0ae1
Revises:
Create Date: 2026-03-20 19:27:55.011303

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d359a92d0ae1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creators",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("division", sa.String(length=32), nullable=False),
        sa.Column("api_key_dev", sa.String(length=128), nullable=True),
        sa.Column("api_key_hash", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("strategy_description", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("avatar_index", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "battles",
        sa.Column("battle_id", sa.String(length=64), nullable=False),
        sa.Column("creator1_id", sa.String(length=64), nullable=False),
        sa.Column("creator2_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("creator1_score", sa.Float(), nullable=True),
        sa.Column("creator2_score", sa.Float(), nullable=True),
        sa.Column("creator1_details", sa.JSON(), nullable=True),
        sa.Column("creator2_details", sa.JSON(), nullable=True),
        sa.Column("winner_id", sa.String(length=64), nullable=True),
        sa.Column("margin", sa.Float(), nullable=True),
        sa.Column("battle_type", sa.String(length=16), nullable=False),
        sa.CheckConstraint("battle_type IN ('MANUAL','AUTO')", name="ck_battle_type"),
        sa.CheckConstraint("status IN ('ACTIVE','RESOLVED')", name="ck_battle_status"),
        sa.CheckConstraint("creator1_id != creator2_id", name="ck_different_creators"),
        sa.ForeignKeyConstraint(
            ["creator1_id"],
            ["creators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator2_id"],
            ["creators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["creators.id"],
        ),
        sa.PrimaryKeyConstraint("battle_id"),
    )
    with op.batch_alter_table("battles", schema=None) as batch_op:
        batch_op.create_index("ix_battles_creator1", ["creator1_id"], unique=False)
        batch_op.create_index("ix_battles_creator2", ["creator2_id"], unique=False)
        batch_op.create_index("ix_battles_status", ["status"], unique=False)

    op.create_table(
        "creator_scores",
        sa.Column("creator_id", sa.String(length=64), nullable=False),
        sa.Column("win_rate", sa.Float(), nullable=False),
        sa.Column("risk_adjusted_return", sa.Float(), nullable=False),
        sa.Column("consistency", sa.Float(), nullable=False),
        sa.Column("confidence_calibration", sa.Float(), nullable=False),
        sa.Column("composite_score", sa.Float(), nullable=False),
        sa.Column("total_signals", sa.Integer(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creators.id"],
        ),
        sa.PrimaryKeyConstraint("creator_id"),
    )
    op.create_table(
        "signals",
        sa.Column("signal_id", sa.String(length=64), nullable=False),
        sa.Column("creator_id", sa.String(length=64), nullable=False),
        sa.Column("asset", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("supporting_data", sa.JSON(), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=True),
        sa.Column("stop_loss", sa.Float(), nullable=True),
        sa.Column("timeframe", sa.String(length=10), nullable=True),
        sa.Column("commitment_hash", sa.String(length=64), nullable=False),
        sa.Column("committed_at", sa.DateTime(), nullable=False),
        sa.Column("outcome", sa.String(length=10), nullable=True),
        sa.Column("outcome_price", sa.Float(), nullable=True),
        sa.Column("outcome_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN ('WIN','LOSS','NEUTRAL')",
            name="ck_outcome_values",
        ),
        sa.CheckConstraint("confidence > 0.0 AND confidence < 1.0", name="ck_confidence_range"),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creators.id"],
        ),
        sa.PrimaryKeyConstraint("signal_id"),
        sa.UniqueConstraint("commitment_hash"),
    )
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.create_index("ix_signals_committed_at", ["committed_at"], unique=False)
        batch_op.create_index("ix_signals_creator_id", ["creator_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.drop_index("ix_signals_creator_id")
        batch_op.drop_index("ix_signals_committed_at")

    op.drop_table("signals")
    op.drop_table("creator_scores")
    with op.batch_alter_table("battles", schema=None) as batch_op:
        batch_op.drop_index("ix_battles_status")
        batch_op.drop_index("ix_battles_creator2")
        batch_op.drop_index("ix_battles_creator1")

    op.drop_table("battles")
    op.drop_table("creators")
    # ### end Alembic commands ###
