"""add_email_verification_columns

Revision ID: dbdb51ff0a27
Revises: 55de4aad29f5
Create Date: 2026-04-18 01:09:50.816633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdb51ff0a27'
down_revision: Union[str, Sequence[str], None] = '55de4aad29f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verify_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_creators_email_verify_token'), ['email_verify_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creators_email_verify_token'))
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verify_token')

    # ### end Alembic commands ###
