"""add tournament_schedules and league_standings tables

Revision ID: f62832412863
Revises: a71d4350bc0d
Create Date: 2026-03-23 10:06:35.585240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62832412863'
down_revision: Union[str, Sequence[str], None] = 'a71d4350bc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_schedules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('recurrence', sa.String(length=16), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=32), nullable=True),
    sa.Column('min_signals', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("format IN ('single_elimination','round_robin')", name='ck_schedule_format'),
    sa.CheckConstraint("recurrence IN ('daily','weekly','custom')", name='ck_schedule_recurrence'),
    sa.CheckConstraint('hour >= 0 AND hour <= 23', name='ck_schedule_hour'),
    sa.CheckConstraint('max_participants >= 2', name='ck_schedule_min_participants'),
    sa.ForeignKeyConstraint(['created_by'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_tournament_schedules_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_tournament_schedules_next_run_at', ['next_run_at'], unique=False)

    op.create_table('league_standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.String(length=64), nullable=False),
    sa.Column('tournaments_played', sa.Integer(), nullable=False),
    sa.Column('tournaments_won', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['tournament_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('league_standings', schema=None) as batch_op:
        batch_op.create_index('ix_league_standings_creator_id', ['creator_id'], unique=False)
        batch_op.create_index('ix_league_standings_schedule_id', ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_standings', schema=None) as batch_op:
        batch_op.drop_index('ix_league_standings_schedule_id')
        batch_op.drop_index('ix_league_standings_creator_id')

    op.drop_table('league_standings')
    with op.batch_alter_table('tournament_schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_tournament_schedules_next_run_at')
        batch_op.drop_index('ix_tournament_schedules_is_active')

    op.drop_table('tournament_schedules')
    # ### end Alembic commands ###
